//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ifly.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Associator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Associator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ifly.Resources.Associator", typeof(Associator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s see....
        /// </summary>
        public static string Comparing {
            get {
                return ResourceManager.GetString("Comparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare things by weight, size and other attributes..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This experiment was created at &lt;a href=&quot;https://spritesapp.com&quot;&gt;Sprites&lt;/a&gt; by using data from &lt;a href=&quot;http://www.wolframalpha.com&quot;&gt;Wolfram|Alpha&lt;/a&gt;. If you found it useful - &lt;a href=&quot;http://twitter.com/spritesapp&quot;&gt;let us know&lt;/a&gt;..
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centimeters.
        /// </summary>
        public static string Measure_Cm {
            get {
                return ResourceManager.GetString("Measure_Cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centimeter.
        /// </summary>
        public static string Measure_Cm_Single {
            get {
                return ResourceManager.GetString("Measure_Cm_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grams.
        /// </summary>
        public static string Measure_G {
            get {
                return ResourceManager.GetString("Measure_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gram.
        /// </summary>
        public static string Measure_G_Single {
            get {
                return ResourceManager.GetString("Measure_G_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilograms.
        /// </summary>
        public static string Measure_Kg {
            get {
                return ResourceManager.GetString("Measure_Kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilogram.
        /// </summary>
        public static string Measure_Kg_Single {
            get {
                return ResourceManager.GetString("Measure_Kg_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometers.
        /// </summary>
        public static string Measure_Km {
            get {
                return ResourceManager.GetString("Measure_Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometer.
        /// </summary>
        public static string Measure_Km_Single {
            get {
                return ResourceManager.GetString("Measure_Km_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meters.
        /// </summary>
        public static string Measure_M {
            get {
                return ResourceManager.GetString("Measure_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meter.
        /// </summary>
        public static string Measure_M_Single {
            get {
                return ResourceManager.GetString("Measure_M_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tons.
        /// </summary>
        public static string Measure_T {
            get {
                return ResourceManager.GetString("Measure_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ton.
        /// </summary>
        public static string Measure_T_Single {
            get {
                return ResourceManager.GetString("Measure_T_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next fact.
        /// </summary>
        public static string NextFact {
            get {
                return ResourceManager.GetString("NextFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found. Try again maybe?.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to previous fact.
        /// </summary>
        public static string PreviousFact {
            get {
                return ResourceManager.GetString("PreviousFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is taking a bit longer, be patient....
        /// </summary>
        public static string TakingLonger {
            get {
                return ResourceManager.GetString("TakingLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your value in.
        /// </summary>
        public static string YourValueIn {
            get {
                return ResourceManager.GetString("YourValueIn", resourceCulture);
            }
        }
    }
}
