//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ifly.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Frontpage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Frontpage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ifly.Resources.Frontpage", typeof(Frontpage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details.
        /// </summary>
        public static string Account_AccountDetails {
            get {
                return ResourceManager.GetString("Account_AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        public static string Account_BasicInformation {
            get {
                return ResourceManager.GetString("Account_BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in, click to logout.
        /// </summary>
        public static string Account_ClickToLogout {
            get {
                return ResourceManager.GetString("Account_ClickToLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company address.
        /// </summary>
        public static string Account_CompanyAddress {
            get {
                return ResourceManager.GetString("Account_CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where&apos;s your company located?.
        /// </summary>
        public static string Account_CompanyAddress_Description {
            get {
                return ResourceManager.GetString("Account_CompanyAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company details.
        /// </summary>
        public static string Account_CompanyDetails {
            get {
                return ResourceManager.GetString("Account_CompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string Account_CompanyName {
            get {
                return ResourceManager.GetString("Account_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s that awesome place you work at?.
        /// </summary>
        public static string Account_CompanyName_Description {
            get {
                return ResourceManager.GetString("Account_CompanyName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One month &quot;Ultimate&quot; plan (${0})..
        /// </summary>
        public static string Account_Payment_Agency_OneMonth {
            get {
                return ResourceManager.GetString("Account_Payment_Agency_OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year &quot;Ultimate&quot; plan (${0})..
        /// </summary>
        public static string Account_Payment_Agency_OneYear {
            get {
                return ResourceManager.GetString("Account_Payment_Agency_OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One month &quot;Free&quot; plan (${0})..
        /// </summary>
        public static string Account_Payment_Basic_OneMonth {
            get {
                return ResourceManager.GetString("Account_Payment_Basic_OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year &quot;Free&quot; plan (${0})..
        /// </summary>
        public static string Account_Payment_Basic_OneYear {
            get {
                return ResourceManager.GetString("Account_Payment_Basic_OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One month &quot;Pro&quot; plan (${0})..
        /// </summary>
        public static string Account_Payment_Pro_OneMonth {
            get {
                return ResourceManager.GetString("Account_Payment_Pro_OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year &quot;Pro&quot; plan (${0})..
        /// </summary>
        public static string Account_Payment_Pro_OneYear {
            get {
                return ResourceManager.GetString("Account_Payment_Pro_OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open editor.
        /// </summary>
        public static string Account_ReturnToEditor {
            get {
                return ResourceManager.GetString("Account_ReturnToEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and pay.
        /// </summary>
        public static string Account_SaveAndPay {
            get {
                return ResourceManager.GetString("Account_SaveAndPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Account_SaveChanges {
            get {
                return ResourceManager.GetString("Account_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved!.
        /// </summary>
        public static string Account_Updated {
            get {
                return ResourceManager.GetString("Account_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string Account_YourEmail {
            get {
                return ResourceManager.GetString("Account_YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We won&apos;t spam you..
        /// </summary>
        public static string Account_YourEmail_Description {
            get {
                return ResourceManager.GetString("Account_YourEmail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already in use..
        /// </summary>
        public static string Account_YourEmail_Exists {
            get {
                return ResourceManager.GetString("Account_YourEmail_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify your contact email..
        /// </summary>
        public static string Account_YourEmail_Required {
            get {
                return ResourceManager.GetString("Account_YourEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string Account_YourName {
            get {
                return ResourceManager.GetString("Account_YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like us to call you?.
        /// </summary>
        public static string Account_YourName_Description {
            get {
                return ResourceManager.GetString("Account_YourName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us your name..
        /// </summary>
        public static string Account_YourName_Required {
            get {
                return ResourceManager.GetString("Account_YourName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string Account_YourPassword {
            get {
                return ResourceManager.GetString("Account_YourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your new password..
        /// </summary>
        public static string Account_YourPassword_Description {
            get {
                return ResourceManager.GetString("Account_YourPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the password..
        /// </summary>
        public static string Account_YourPassword_Required {
            get {
                return ResourceManager.GetString("Account_YourPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string Account_YourPasswordChange_Description {
            get {
                return ResourceManager.GetString("Account_YourPasswordChange_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your plan.
        /// </summary>
        public static string Account_YourPlan {
            get {
                return ResourceManager.GetString("Account_YourPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare plans.
        /// </summary>
        public static string Account_YourPlan_ComparePlans {
            get {
                return ResourceManager.GetString("Account_YourPlan_ComparePlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your plan..
        /// </summary>
        public static string Account_YourPlan_Description {
            get {
                return ResourceManager.GetString("Account_YourPlan_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our private beta program and test the new features &lt;strong&gt;for free&lt;/strong&gt;!.
        /// </summary>
        public static string AgencyBeta {
            get {
                return ResourceManager.GetString("AgencyBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our private beta program and test video infographics &lt;strong&gt;for free&lt;/strong&gt;!.
        /// </summary>
        public static string AgencyBetaVideo {
            get {
                return ResourceManager.GetString("AgencyBetaVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? &lt;a href=&quot;javascript:void(0);&quot; rel=&quot;nofollow&quot; onclick=&quot;Ifly.App.getInstance().login(); return false;&quot;&gt;Sign in&lt;/a&gt;.
        /// </summary>
        public static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your inbox!.
        /// </summary>
        public static string CheckYourEmail {
            get {
                return ResourceManager.GetString("CheckYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: You won&apos;t be able to save your changes or publish your infographic in this mode..
        /// </summary>
        public static string DemoSignInNote {
            get {
                return ResourceManager.GetString("DemoSignInNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites is a free tool for creating beautiful animated infographics for the Web..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;border:none;margin:0;padding:50px;background-color:#f4f4f4;font-family:Verdana;font-size:13px;font-color:#333333;&quot;&gt;&lt;table style=&quot;border:1px solid #c3c3c3;margin:0 auto;padding:0;background-color:#fff;width:500px;display:block;&quot;&gt;&lt;tr style=&quot;vertical-align:middle;&quot;&gt;&lt;td style=&quot;vertical-align:middle;padding:10px 30px;padding-bottom:0;padding-top: 20px;&quot;&gt;&lt;a href=&quot;https://spritesapp.com&quot;&gt;&lt;img src=&quot;https://spritesapp.com/assets/img/sprites-email-header.jpg&quot; style=&quot;width:120px;height:68px;border:none;mar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Email_PasswordReset_Body {
            get {
                return ResourceManager.GetString("Email_PasswordReset_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites password reset.
        /// </summary>
        public static string Email_PasswordReset_Subject {
            get {
                return ResourceManager.GetString("Email_PasswordReset_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;border:none;margin:0;padding:50px;background-color:#f4f4f4;font-family:Verdana;font-size:13px;font-color:#333333;&quot;&gt;&lt;table style=&quot;border:1px solid #c3c3c3;margin:0 auto;padding:0;background-color:#fff;width:500px;display:block;&quot;&gt;&lt;tr style=&quot;vertical-align:middle;&quot;&gt;&lt;td style=&quot;vertical-align:middle;padding:10px 30px;padding-bottom:0;padding-top: 20px;&quot;&gt;&lt;a href=&quot;https://spritesapp.com&quot;&gt;&lt;img src=&quot;https://spritesapp.com/assets/img/sprites-email-header.jpg&quot; style=&quot;width:120px;height:68px;border:none;mar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Email_PresentationSharing_Body {
            get {
                return ResourceManager.GetString("Email_PresentationSharing_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No title].
        /// </summary>
        public static string Email_PresentationSharing_NoTitle {
            get {
                return ResourceManager.GetString("Email_PresentationSharing_NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites infographic sharing.
        /// </summary>
        public static string Email_PresentationSharing_Subject {
            get {
                return ResourceManager.GetString("Email_PresentationSharing_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;border:none;margin:0;padding:50px;background-color:#f4f4f4;font-family:Verdana;font-size:13px;font-color:#333333;&quot;&gt;&lt;table style=&quot;border:1px solid #c3c3c3;margin:0 auto;padding:0;background-color:#fff;width:500px;display:block;&quot;&gt;&lt;tr style=&quot;vertical-align:middle;&quot;&gt;&lt;td style=&quot;vertical-align:middle;padding:10px 30px;padding-bottom:0;padding-top: 20px;&quot;&gt;&lt;a href=&quot;https://spritesapp.com&quot;&gt;&lt;img src=&quot;https://spritesapp.com/assets/img/sprites-email-header.jpg&quot; style=&quot;width:120px;height:68px;border:none;mar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Email_SubscriptionExpiring_Body {
            get {
                return ResourceManager.GetString("Email_SubscriptionExpiring_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Sprites subscription is expiring.
        /// </summary>
        public static string Email_SubscriptionExpiring_Subject {
            get {
                return ResourceManager.GetString("Email_SubscriptionExpiring_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;border:none;margin:0;padding:50px;background-color:#f4f4f4;font-family:Verdana;font-size:13px;font-color:#333333;&quot;&gt;&lt;table style=&quot;border:1px solid #c3c3c3;margin:0 auto;padding:0;background-color:#fff;width:500px;display:block;&quot;&gt;&lt;tr style=&quot;vertical-align:middle;&quot;&gt;&lt;td style=&quot;vertical-align:middle;padding:10px 30px;padding-bottom:0;padding-top: 20px;&quot;&gt;&lt;a href=&quot;https://spritesapp.com&quot;&gt;&lt;img src=&quot;https://spritesapp.com/assets/img/sprites-email-header.jpg&quot; style=&quot;width:120px;height:68px;border:none;mar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Email_ValidateEmail_Body {
            get {
                return ResourceManager.GetString("Email_ValidateEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites account confirmation.
        /// </summary>
        public static string Email_ValidateEmail_Subject {
            get {
                return ResourceManager.GetString("Email_ValidateEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example infographics.
        /// </summary>
        public static string ExampleInfographics {
            get {
                return ResourceManager.GetString("ExampleInfographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee love.
        /// </summary>
        public static string Examples_Coffee {
            get {
                return ResourceManager.GetString("Examples_Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how much the average American spends on (and consumes) coffee and who are the big players on the market..
        /// </summary>
        public static string Examples_Coffee_Description {
            get {
                return ResourceManager.GetString("Examples_Coffee_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubai airport.
        /// </summary>
        public static string Examples_Dxb {
            get {
                return ResourceManager.GetString("Examples_Dxb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This infographic focuses on the size and capacity of one of the largest airport in the World - Dubai International (DXB)..
        /// </summary>
        public static string Examples_Dxb_Description {
            get {
                return ResourceManager.GetString("Examples_Dxb_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time on Internet.
        /// </summary>
        public static string Examples_Internet {
            get {
                return ResourceManager.GetString("Examples_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s see how much time people spend on Internet and how quickly this medium has grown over the recent years..
        /// </summary>
        public static string Examples_Internet_Description {
            get {
                return ResourceManager.GetString("Examples_Internet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facts about sleep.
        /// </summary>
        public static string Examples_Sleep {
            get {
                return ResourceManager.GetString("Examples_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out how much sleep is enough (and how much is not),  which country gets most sleep and other interesting facts..
        /// </summary>
        public static string Examples_Sleep_Description {
            get {
                return ResourceManager.GetString("Examples_Sleep_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The power of widgets.
        /// </summary>
        public static string Examples_Widgets {
            get {
                return ResourceManager.GetString("Examples_Widgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quick example demonstrates some of the cool things you can do by using widgets in your infographics..
        /// </summary>
        public static string Examples_Widgets_Description {
            get {
                return ResourceManager.GetString("Examples_Widgets_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites offers rich selection of building blocks for you to choose from. Text, charts, maps, tables, images, progress bars and more - all of this will make your presentations speak for themselves like never before..
        /// </summary>
        public static string Features_Blocks_Description {
            get {
                return ResourceManager.GetString("Features_Blocks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety of building blocks.
        /// </summary>
        public static string Features_Blocks_Title {
            get {
                return ResourceManager.GetString("Features_Blocks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites offers a unique collaboration functionality that will empower your team and improve your organization&apos;s workflow, whether you are big or small. Easy sharing, live collaborative editing and team chat - working together on your infographics has never been easier..
        /// </summary>
        public static string Features_Collaboration_Description {
            get {
                return ResourceManager.GetString("Features_Collaboration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborate like never before.
        /// </summary>
        public static string Features_Collaboration_Title {
            get {
                return ResourceManager.GetString("Features_Collaboration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites is also very developer-friendly: there&apos;s a number of ways you can extend the platfom if you know how to write code. For example, you can create your own elements (widgets) or make your own themes. Documentation as well as code examples are available on GitHub..
        /// </summary>
        public static string Features_Developer_Description {
            get {
                return ResourceManager.GetString("Features_Developer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer-friendly.
        /// </summary>
        public static string Features_Developer_Title {
            get {
                return ResourceManager.GetString("Features_Developer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual slides can be exported as JPG images which is great for making previews, thumbnails or even displaying a complete presentation as an image gallery. You can also download your entire presentation as a single PDF document..
        /// </summary>
        public static string Features_DownloadImage_Description {
            get {
                return ResourceManager.GetString("Features_DownloadImage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download as JPG or PDF.
        /// </summary>
        public static string Features_DownloadImage_Title {
            get {
                return ResourceManager.GetString("Features_DownloadImage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites editor is very intuitive and easy to use. We are handling all the complexity so you can focus on what is truly important - your visual story..
        /// </summary>
        public static string Features_EaseOfUse_Description {
            get {
                return ResourceManager.GetString("Features_EaseOfUse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple and intuitive.
        /// </summary>
        public static string Features_EaseOfUse_Title {
            get {
                return ResourceManager.GetString("Features_EaseOfUse_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites is built on top of latest and greatest from HTML5 technology stack which includes great typography, slick animations, smooth shadows and gradients and many more..
        /// </summary>
        public static string Features_HTML5_Description {
            get {
                return ResourceManager.GetString("Features_HTML5_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML5 at its best.
        /// </summary>
        public static string Features_HTML5_Title {
            get {
                return ResourceManager.GetString("Features_HTML5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites can take your data residing in Excel file, Google Spreadsheet or under the custom URL and import it into your presentation. This is especially useful when showing charts from calculations that you made previously and that you would like to now publish. .
        /// </summary>
        public static string Features_Import_Description {
            get {
                return ResourceManager.GetString("Features_Import_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data import.
        /// </summary>
        public static string Features_Import_Title {
            get {
                return ResourceManager.GetString("Features_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites makes it extremely easy to display real-time data in your presentations. You can connect to Google Sheets, custom URL or Google Analytics. And it&apos;s not limited to charts and tables - every building block (including text and images) can display live data..
        /// </summary>
        public static string Features_LiveData_Description {
            get {
                return ResourceManager.GetString("Features_LiveData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect live data.
        /// </summary>
        public static string Features_LiveData_Title {
            get {
                return ResourceManager.GetString("Features_LiveData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites combines best practices of creating infographics with the flexibility of a normal multi-slide presentation. This unique approach makes it possible to compose exceptional visual stories..
        /// </summary>
        public static string Features_MultiSlide_Description {
            get {
                return ResourceManager.GetString("Features_MultiSlide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-slide layout.
        /// </summary>
        public static string Features_MultiSlide_Title {
            get {
                return ResourceManager.GetString("Features_MultiSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Sprites presentation can be additionally secured with the password so that you can safely share sensitive information with your peers. And in case you have changed your mind, you can always make the presentation public again..
        /// </summary>
        public static string Features_Password_Description {
            get {
                return ResourceManager.GetString("Features_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public vs. private content.
        /// </summary>
        public static string Features_Password_Title {
            get {
                return ResourceManager.GetString("Features_Password_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sprites presentations (with no exception) are fully responsive meaning that they look great on pretty much any resolution, from mobile phone to projector. Same applies when you are inserting presentations on your website or blog: they will automagically scale to match the width of your content..
        /// </summary>
        public static string Features_Responsive_Description {
            get {
                return ResourceManager.GetString("Features_Responsive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive, embeddable.
        /// </summary>
        public static string Features_Responsive_Title {
            get {
                return ResourceManager.GetString("Features_Responsive_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Sprites sharing your visual masterpiece has never been easier. Click an icon and let your friends and followers know what you&apos;re up to and check out your work. .
        /// </summary>
        public static string Features_Sharing_Description {
            get {
                return ResourceManager.GetString("Features_Sharing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-click social sharing.
        /// </summary>
        public static string Features_Sharing_Title {
            get {
                return ResourceManager.GetString("Features_Sharing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are striving to provide every single user with the best possible Sprites experience. Don&apos;t hesitate to contact us if you have any questions or need help - we are always there for you..
        /// </summary>
        public static string Features_Support_Description {
            get {
                return ResourceManager.GetString("Features_Support_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazing email support.
        /// </summary>
        public static string Features_Support_Title {
            get {
                return ResourceManager.GetString("Features_Support_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a great selection of colorful, unique built-in themes for every mood, and every occasion. And in case you need a custom (branded) theme, it is super-easy to create your own from scratch or extend existing one..
        /// </summary>
        public static string Features_Themes_Description {
            get {
                return ResourceManager.GetString("Features_Themes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorful themes.
        /// </summary>
        public static string Features_Themes_Title {
            get {
                return ResourceManager.GetString("Features_Themes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product features.
        /// </summary>
        public static string Features_Title {
            get {
                return ResourceManager.GetString("Features_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your entire presentation can be turned into an HD video. You can additionally specify an audio file which is great for adding background music or narration. You can also choose to let Sprites upload your video on YouTube for you..
        /// </summary>
        public static string Features_Video_Description {
            get {
                return ResourceManager.GetString("Features_Video_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn it into a video.
        /// </summary>
        public static string Features_Video_Title {
            get {
                return ResourceManager.GetString("Features_Video_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send us your comments, feature requests or bug reports (check out our &lt;a href=&quot;http://spritesapp.uservoice.com&quot;&gt;support page&lt;/a&gt; and &lt;a href=&quot;http://blog.spritesapp.com&quot;&gt;blog&lt;/a&gt; as well). We appreciate all the feedback and will gladly answer every email. Thank you!.
        /// </summary>
        public static string Feedback_Body {
            get {
                return ResourceManager.GetString("Feedback_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beautiful animated infographics and online presentations. Quick and easy..
        /// </summary>
        public static string Headline {
            get {
                return ResourceManager.GetString("Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires &quot;Ultimate&quot; subscription..
        /// </summary>
        public static string Info_RequiresAgency {
            get {
                return ResourceManager.GetString("Info_RequiresAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please re-submit your password reset request..
        /// </summary>
        public static string Info_ResetTokenExpired {
            get {
                return ResourceManager.GetString("Info_ResetTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See it yourself.
        /// </summary>
        public static string JoinFamily {
            get {
                return ResourceManager.GetString("JoinFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to create infographics here: &lt;a href=&quot;http://blog.spritesapp.com/2014/05/21/creating-your-first-infographic.html&quot;&gt;Creating your first infographic&lt;/a&gt;.
        /// </summary>
        public static string LearnHowTo {
            get {
                return ResourceManager.GetString("LearnHowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make video infographics.
        /// </summary>
        public static string MakeVideoInfographics {
            get {
                return ResourceManager.GetString("MakeVideoInfographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make videos.
        /// </summary>
        public static string MakeVideos {
            get {
                return ResourceManager.GetString("MakeVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own.
        /// </summary>
        public static string MakeYourOwn {
            get {
                return ResourceManager.GetString("MakeYourOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who we are.
        /// </summary>
        public static string MeetTheTeam {
            get {
                return ResourceManager.GetString("MeetTheTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent!.
        /// </summary>
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account.
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New!.
        /// </summary>
        public static string NewFeature {
            get {
                return ResourceManager.GetString("NewFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest blog posts.
        /// </summary>
        public static string News_Blog {
            get {
                return ResourceManager.GetString("News_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load posts right now. Go to &lt;a href=&quot;http://blog.spritesapp.com&quot;&gt;blog.spritesapp.com/spritesapp&lt;/a&gt; to get the latest updates..
        /// </summary>
        public static string News_NoPosts {
            get {
                return ResourceManager.GetString("News_NoPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load tweets right now. Go to &lt;a href=&quot;https://twitter.com/spritesapp&quot;&gt;twitter.com/spritesapp&lt;/a&gt; to get the latest updates..
        /// </summary>
        public static string News_NoTweets {
            get {
                return ResourceManager.GetString("News_NoTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest tweets.
        /// </summary>
        public static string News_Twitter {
            get {
                return ResourceManager.GetString("News_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News and updates.
        /// </summary>
        public static string NewsAndUpdates {
            get {
                return ResourceManager.GetString("NewsAndUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal sign in.
        /// </summary>
        public static string NormalSignIn {
            get {
                return ResourceManager.GetString("NormalSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enabled.
        /// </summary>
        public static string NotEnabled {
            get {
                return ResourceManager.GetString("NotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One moment....
        /// </summary>
        public static string OneMoment {
            get {
                return ResourceManager.GetString("OneMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or watch the video.
        /// </summary>
        public static string OrWatchTheVideo {
            get {
                return ResourceManager.GetString("OrWatchTheVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal account.
        /// </summary>
        public static string Payment_ChargedToPayPal {
            get {
                return ResourceManager.GetString("Payment_ChargedToPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply payment.
        /// </summary>
        public static string Payment_ChoosePaymentMethod {
            get {
                return ResourceManager.GetString("Payment_ChoosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One month.
        /// </summary>
        public static string Payment_Duration_OneMonth {
            get {
                return ResourceManager.GetString("Payment_Duration_OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One year.
        /// </summary>
        public static string Payment_Duration_OneYear {
            get {
                return ResourceManager.GetString("Payment_Duration_OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments no longer accepted.
        /// </summary>
        public static string Payment_NotAccepted {
            get {
                return ResourceManager.GetString("Payment_NotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay&lt;span&gt;&amp;nbsp;&lt;/span&gt;with card.
        /// </summary>
        public static string Payment_PayWithCard {
            get {
                return ResourceManager.GetString("Payment_PayWithCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay&lt;span&gt;&amp;nbsp;&lt;/span&gt;with PayPal.
        /// </summary>
        public static string Payment_PayWithPayPal {
            get {
                return ResourceManager.GetString("Payment_PayWithPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Step 1&lt;/strong&gt;. Choose subscription period.
        /// </summary>
        public static string Payment_PleaseChooseDuration {
            get {
                return ResourceManager.GetString("Payment_PleaseChooseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Step 2&lt;/strong&gt;. Choose payment method.
        /// </summary>
        public static string Payment_PleaseChoosePaymentMethod {
            get {
                return ResourceManager.GetString("Payment_PleaseChoosePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment didn&apos;t go through (your card wasn&apos;t charged). Please try again..
        /// </summary>
        public static string PaymentError_InternalError {
            get {
                return ResourceManager.GetString("PaymentError_InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment history.
        /// </summary>
        public static string PaymentHistory {
            get {
                return ResourceManager.GetString("PaymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string PaymentHistory_Account {
            get {
                return ResourceManager.GetString("PaymentHistory_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string PaymentHistory_Amount {
            get {
                return ResourceManager.GetString("PaymentHistory_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PaymentHistory_Date {
            get {
                return ResourceManager.GetString("PaymentHistory_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download receipt.
        /// </summary>
        public static string PaymentHistory_DownloadReceipt {
            get {
                return ResourceManager.GetString("PaymentHistory_DownloadReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payments have been made so far..
        /// </summary>
        public static string PaymentHistory_Empty {
            get {
                return ResourceManager.GetString("PaymentHistory_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string PaymentHistory_Receipt {
            get {
                return ResourceManager.GetString("PaymentHistory_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment has been accepted. Thank you!.
        /// </summary>
        public static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay now.
        /// </summary>
        public static string PayNow {
            get {
                return ResourceManager.GetString("PayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy to Use.
        /// </summary>
        public static string Pitch_1 {
            get {
                return ResourceManager.GetString("Pitch_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a good set of visual elements and built-in themes composing your infographic becomes super-easy..
        /// </summary>
        public static string Pitch_1_Description {
            get {
                return ResourceManager.GetString("Pitch_1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free and Open.
        /// </summary>
        public static string Pitch_2 {
            get {
                return ResourceManager.GetString("Pitch_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The basic version of Sprites is absolutely free for everybody and all infographics are released under Creative Commons license..
        /// </summary>
        public static string Pitch_2_Description {
            get {
                return ResourceManager.GetString("Pitch_2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embracing the Web.
        /// </summary>
        public static string Pitch_3 {
            get {
                return ResourceManager.GetString("Pitch_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything in Sprites is 100% HTML5-based and plugin-free. There&apos;s no Flash or any other proprietary technology used..
        /// </summary>
        public static string Pitch_3_Description {
            get {
                return ResourceManager.GetString("Pitch_3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Scalable.
        /// </summary>
        public static string Pitch_4 {
            get {
                return ResourceManager.GetString("Pitch_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites infographics utilize the newest responsive design techniques and should look good on pretty much any device..
        /// </summary>
        public static string Pitch_4_Description {
            get {
                return ResourceManager.GetString("Pitch_4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile-Ready.
        /// </summary>
        public static string Pitch_5 {
            get {
                return ResourceManager.GetString("Pitch_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We try to make Sprites infographics shine on as many platforms as possible. You can already try it on your iPhone and iPad..
        /// </summary>
        public static string Pitch_5_Description {
            get {
                return ResourceManager.GetString("Pitch_5_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer-Friendly.
        /// </summary>
        public static string Pitch_6 {
            get {
                return ResourceManager.GetString("Pitch_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JavaScript SDK plus the guidelines on making your own themes are available at &lt;a href=&quot;https://github.com/spritesapp&quot;&gt;github.com/spritesapp&lt;/a&gt;..
        /// </summary>
        public static string Pitch_6_Description {
            get {
                return ResourceManager.GetString("Pitch_6_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate.
        /// </summary>
        public static string Plan_Agency {
            get {
                return ResourceManager.GetString("Plan_Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the &quot;Pro&quot; features.
        /// </summary>
        public static string Plan_Agency_Feature1 {
            get {
                return ResourceManager.GetString("Plan_Agency_Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export infographic to a video.
        /// </summary>
        public static string Plan_Agency_Feature2 {
            get {
                return ResourceManager.GetString("Plan_Agency_Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority support.
        /// </summary>
        public static string Plan_Agency_Feature3 {
            get {
                return ResourceManager.GetString("Plan_Agency_Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect live data.
        /// </summary>
        public static string Plan_Agency_Feature4 {
            get {
                return ResourceManager.GetString("Plan_Agency_Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube auto-upload.
        /// </summary>
        public static string Plan_Agency_Feature5 {
            get {
                return ResourceManager.GetString("Plan_Agency_Feature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborate in real time.
        /// </summary>
        public static string Plan_Agency_Feature6 {
            get {
                return ResourceManager.GetString("Plan_Agency_Feature6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $9&lt;small&gt;/mo&lt;/small&gt;.
        /// </summary>
        public static string Plan_Agency_Figure {
            get {
                return ResourceManager.GetString("Plan_Agency_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or &lt;span class=&quot;highlight&quot;&gt;$81&lt;/span&gt; a year (save 25%).
        /// </summary>
        public static string Plan_Agency_Transcript {
            get {
                return ResourceManager.GetString("Plan_Agency_Transcript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Plan_Free {
            get {
                return ResourceManager.GetString("Plan_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the basic features.
        /// </summary>
        public static string Plan_Free_Description {
            get {
                return ResourceManager.GetString("Plan_Free_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $0.
        /// </summary>
        public static string Plan_Free_Figure {
            get {
                return ResourceManager.GetString("Plan_Free_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely free..
        /// </summary>
        public static string Plan_Free_Transcript {
            get {
                return ResourceManager.GetString("Plan_Free_Transcript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro.
        /// </summary>
        public static string Plan_Pro {
            get {
                return ResourceManager.GetString("Plan_Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New building blocks.
        /// </summary>
        public static string Plan_Pro_Feature1 {
            get {
                return ResourceManager.GetString("Plan_Pro_Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich text editing.
        /// </summary>
        public static string Plan_Pro_Feature2 {
            get {
                return ResourceManager.GetString("Plan_Pro_Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four new amazing themes.
        /// </summary>
        public static string Plan_Pro_Feature3 {
            get {
                return ResourceManager.GetString("Plan_Pro_Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to upload custom themes.
        /// </summary>
        public static string Plan_Pro_Feature4 {
            get {
                return ResourceManager.GetString("Plan_Pro_Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sprites branding.
        /// </summary>
        public static string Plan_Pro_Feature5 {
            get {
                return ResourceManager.GetString("Plan_Pro_Feature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infographic statistics.
        /// </summary>
        public static string Plan_Pro_Feature6 {
            get {
                return ResourceManager.GetString("Plan_Pro_Feature6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics integration.
        /// </summary>
        public static string Plan_Pro_Feature7 {
            get {
                return ResourceManager.GetString("Plan_Pro_Feature7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download infographic as an image.
        /// </summary>
        public static string Plan_Pro_Feature8 {
            get {
                return ResourceManager.GetString("Plan_Pro_Feature8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password-protected infographics.
        /// </summary>
        public static string Plan_Pro_Feature9 {
            get {
                return ResourceManager.GetString("Plan_Pro_Feature9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $3&lt;small&gt;/mo&lt;/small&gt;.
        /// </summary>
        public static string Plan_Pro_Figure {
            get {
                return ResourceManager.GetString("Plan_Pro_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or &lt;span class=&quot;highlight&quot;&gt;$27&lt;/span&gt; a year (save 25%).
        /// </summary>
        public static string Plan_Pro_Transcript {
            get {
                return ResourceManager.GetString("Plan_Pro_Transcript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have reset your password. Please specify a new one now..
        /// </summary>
        public static string PleaseChangeYourPassword {
            get {
                return ResourceManager.GetString("PleaseChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string PleaseSignIn {
            get {
                return ResourceManager.GetString("PleaseSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month-to-month billing is when you only pay for one month and you are not automatically charged for the following one. This way it is more convenient for you as it allows you to easily switch between different plans and protects you from potentially unwanted long term commitments..
        /// </summary>
        public static string Pricing_FAQ_1_A {
            get {
                return ResourceManager.GetString("Pricing_FAQ_1_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is month-to-month billing?.
        /// </summary>
        public static string Pricing_FAQ_1_Q {
            get {
                return ResourceManager.GetString("Pricing_FAQ_1_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply go to &lt;a href=&quot;https://spritesapp.com/account&quot;&gt;spritesapp.com/account&lt;/a&gt;, choose a different plan and click &quot;Save changes&quot;..
        /// </summary>
        public static string Pricing_FAQ_2_A {
            get {
                return ResourceManager.GetString("Pricing_FAQ_2_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I upgrade to a different plan?.
        /// </summary>
        public static string Pricing_FAQ_2_Q {
            get {
                return ResourceManager.GetString("Pricing_FAQ_2_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t need to! As we mentioned, all the payments are non-recurring which means that at the end of the billing period (one month) your subscription will expire and you can either renew your month-to-month subscription by submitting another payment or switch to our free plan..
        /// </summary>
        public static string Pricing_FAQ_3_A {
            get {
                return ResourceManager.GetString("Pricing_FAQ_3_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I cancel my plan?.
        /// </summary>
        public static string Pricing_FAQ_3_Q {
            get {
                return ResourceManager.GetString("Pricing_FAQ_3_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing! All the visual content you have previously created under your paid plan will continue to work even after you switch to our free plan. We do not lock or disable anything related to your data or the content you have already published, but you will only be able to edit your existing content under the free plan feature-set..
        /// </summary>
        public static string Pricing_FAQ_4_A {
            get {
                return ResourceManager.GetString("Pricing_FAQ_4_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens to my work when I cancel my plan?.
        /// </summary>
        public static string Pricing_FAQ_4_Q {
            get {
                return ResourceManager.GetString("Pricing_FAQ_4_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitely! If you are a student or a non-for-profit organization and wish to test out one of our advanced plans, simply contact us at &lt;a href=&quot;mailto:contact@spritesapp.com&quot;&gt;contact@spritesapp.com&lt;/a&gt; and we will figure something out!.
        /// </summary>
        public static string Pricing_FAQ_5_A {
            get {
                return ResourceManager.GetString("Pricing_FAQ_5_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any options for students/non-profits?.
        /// </summary>
        public static string Pricing_FAQ_5_Q {
            get {
                return ResourceManager.GetString("Pricing_FAQ_5_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string Pricing_FAQ_Title {
            get {
                return ResourceManager.GetString("Pricing_FAQ_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing FAQ.
        /// </summary>
        public static string Pricing_Toolbar_FAQ {
            get {
                return ResourceManager.GetString("Pricing_Toolbar_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request free trial.
        /// </summary>
        public static string Pricing_Toolbar_FreeTrial {
            get {
                return ResourceManager.GetString("Pricing_Toolbar_FreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While we&apos;re not ready yet to accept payments, the Pro subscription is &lt;strong&gt;free of charge&lt;/strong&gt;!.
        /// </summary>
        public static string ProBeta {
            get {
                return ResourceManager.GetString("ProBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to top.
        /// </summary>
        public static string ScrollToTop {
            get {
                return ResourceManager.GetString("ScrollToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See other features.
        /// </summary>
        public static string SeeFullList {
            get {
                return ResourceManager.GetString("SeeFullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string SendingMessage {
            get {
                return ResourceManager.GetString("SendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send messsage.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing in you are accepting our &lt;a target=&quot;_blank&quot; href=&quot;/tos&quot;&gt;terms of service&lt;/a&gt; and &lt;a target=&quot;_blank&quot; href=&quot;/privacy&quot;&gt;privacy policy&lt;/a&gt;..
        /// </summary>
        public static string SignIn_AcceptTerms {
            get {
                return ResourceManager.GetString("SignIn_AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try out demo version.
        /// </summary>
        public static string SignIn_Demo {
            get {
                return ResourceManager.GetString("SignIn_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Facebook.
        /// </summary>
        public static string SignIn_Facebook {
            get {
                return ResourceManager.GetString("SignIn_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Google.
        /// </summary>
        public static string SignIn_Google {
            get {
                return ResourceManager.GetString("SignIn_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Twitter.
        /// </summary>
        public static string SignIn_Twitter {
            get {
                return ResourceManager.GetString("SignIn_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sprites account.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost finished....
        /// </summary>
        public static string SignUp_Success {
            get {
                return ResourceManager.GetString("SignUp_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re almost there! We&apos;ve just sent you an email with the link to verify your account. .
        /// </summary>
        public static string SignUp_Success_Description {
            get {
                return ResourceManager.GetString("SignUp_Success_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join for free.
        /// </summary>
        public static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUpSubscriptionButton {
            get {
                return ResourceManager.GetString("SignUpSubscriptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites - Blog.
        /// </summary>
        public static string Social_Blog {
            get {
                return ResourceManager.GetString("Social_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites - Facebook.
        /// </summary>
        public static string Social_Facebook {
            get {
                return ResourceManager.GetString("Social_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites - Twitter.
        /// </summary>
        public static string Social_Twitter {
            get {
                return ResourceManager.GetString("Social_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social sign in.
        /// </summary>
        public static string SocialSignIn {
            get {
                return ResourceManager.GetString("SocialSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start making videos.
        /// </summary>
        public static string StartMakingVideos {
            get {
                return ResourceManager.GetString("StartMakingVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed!.
        /// </summary>
        public static string Subscribed {
            get {
                return ResourceManager.GetString("Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string SubscribeToNewsletter {
            get {
                return ResourceManager.GetString("SubscribeToNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pay for your plan to continue using Sprites..
        /// </summary>
        public static string SubscriptionExpired {
            get {
                return ResourceManager.GetString("SubscriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string SubscriptionPlans {
            get {
                return ResourceManager.GetString("SubscriptionPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites is shutting down on August 1st, 2016. &lt;a href=&quot;http://blog.spritesapp.com/2016/05/08/sprites-is-shutting-down.html&quot;&gt;Read the statement&lt;/a&gt;.
        /// </summary>
        public static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavel Volgarev.
        /// </summary>
        public static string Team_PavelVolgarev {
            get {
                return ResourceManager.GetString("Team_PavelVolgarev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder/Developer.
        /// </summary>
        public static string Team_PavelVolgarev_Roles {
            get {
                return ResourceManager.GetString("Team_PavelVolgarev_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although we&apos;re not currently hiring, you&apos;re always welcome to drop us an email and say Hello!.
        /// </summary>
        public static string Team_SayHello {
            get {
                return ResourceManager.GetString("Team_SayHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timofey Voronov.
        /// </summary>
        public static string Team_TimofeyVoronov {
            get {
                return ResourceManager.GetString("Team_TimofeyVoronov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string Team_TimofeyVoronov_Roles {
            get {
                return ResourceManager.GetString("Team_TimofeyVoronov_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You?.
        /// </summary>
        public static string Team_You {
            get {
                return ResourceManager.GetString("Team_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is FANTASTIC! And very easy to use. I cannot wait to plug in all my data to tell stories..
        /// </summary>
        public static string Testimonial_1 {
            get {
                return ResourceManager.GetString("Testimonial_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikki DeLeon, &lt;span&gt;Ava Anderson Non Toxic&lt;/span&gt;.
        /// </summary>
        public static string Testimonial_1_Author {
            get {
                return ResourceManager.GetString("Testimonial_1_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi Guys - LOVE LOVE LOVE this app..
        /// </summary>
        public static string Testimonial_2 {
            get {
                return ResourceManager.GetString("Testimonial_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lindsay Lyons, &lt;span&gt;Dell&lt;/span&gt;.
        /// </summary>
        public static string Testimonial_2_Author {
            get {
                return ResourceManager.GetString("Testimonial_2_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome product, I&apos;m going to start playing with it asap..
        /// </summary>
        public static string Testimonial_3 {
            get {
                return ResourceManager.GetString("Testimonial_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michael Reen, &lt;span&gt;Bleepr&lt;/span&gt;.
        /// </summary>
        public static string Testimonial_3_Author {
            get {
                return ResourceManager.GetString("Testimonial_3_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create infographics and online presentations | Sprites.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites - beautiful infographics..
        /// </summary>
        public static string Title_Share {
            get {
                return ResourceManager.GetString("Title_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll up.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to switch to a new plan? &lt;a href=&quot;https://spritesapp.com/account&quot;&gt;Go to your account&lt;/a&gt;.
        /// </summary>
        public static string UpgradePlan {
            get {
                return ResourceManager.GetString("UpgradePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to unlock great features!.
        /// </summary>
        public static string UpgradeToUnlock {
            get {
                return ResourceManager.GetString("UpgradeToUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert your entire infographic into a video in just a couple of clicks..
        /// </summary>
        public static string VideoPitch_1 {
            get {
                return ResourceManager.GetString("VideoPitch_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally specify an audio file - great for adding music or narration..
        /// </summary>
        public static string VideoPitch_2 {
            get {
                return ResourceManager.GetString("VideoPitch_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download your video and share it with your audience the way you want..
        /// </summary>
        public static string VideoPitch_3 {
            get {
                return ResourceManager.GetString("VideoPitch_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch example infographic.
        /// </summary>
        public static string WatchExampleInfographic {
            get {
                return ResourceManager.GetString("WatchExampleInfographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch the video.
        /// </summary>
        public static string WatchTheVideo {
            get {
                return ResourceManager.GetString("WatchTheVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Sprites.
        /// </summary>
        public static string WelcomeToSprites {
            get {
                return ResourceManager.GetString("WelcomeToSprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there! Just so you know, we use cookies. &lt;a href=&quot;/privacy&quot;&gt;Learn more&lt;/a&gt;.
        /// </summary>
        public static string WeUseCookies {
            get {
                return ResourceManager.GetString("WeUseCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge and dismiss.
        /// </summary>
        public static string WeUseCookies_Dismiss {
            get {
                return ResourceManager.GetString("WeUseCookies_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is this?.
        /// </summary>
        public static string WhatIsThis {
            get {
                return ResourceManager.GetString("WhatIsThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string WhatOurUsersSay {
            get {
                return ResourceManager.GetString("WhatOurUsersSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What our users say.
        /// </summary>
        public static string WhatOurUsersSay_Long {
            get {
                return ResourceManager.GetString("WhatOurUsersSay_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email (optional, won&apos;t be shared).
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        public static string YourEmailSubscribe {
            get {
                return ResourceManager.GetString("YourEmailSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to tell us?.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
